# See https://github.com/Jikoo/EnchantableBlocks/wiki/Configuration
#

autosave: 5
blocks:
  EnchantableFurnace:
    enabled: true
    fortuneListIsBlacklist: true
    fortuneList:
    - wet_sponge
    - stone_bricks
    tableEnchantability: STONE
    tableDisabledEnchantments: []
    tableEnchantmentConflicts:
      silk_touch:
      - fortune
    anvilDisabledEnchantments: []
    anvilEnchantmentConflicts:
      silk_touch:
      - fortune
    anvilEnchantmentMax:
      efficiency: 5
      unbreaking: 3
      fortune: 3
      silk_touch: 1
    overrides:
      "lame_vanilla_world":
        enabled: false
      "lame_vanilla_world_nether":
        enabled: false
      "lame_vanilla_world_the_end":
        enabled: false
      "busted_endgame_bullhonkey_world":
        tableEnchantability: GOLD_ARMOR
        tableEnchantmentConflicts:
        anvilEnchantmentConflicts:
        anvilEnchantmentMax:
          efficiency: 10
          unbreaking: 10
          fortune: 10
