name: EnchantableBlocks

main: com.github.jikoo.enchantableblocks.EnchantableBlocksPlugin
version: ${project.version}
author: Jikoo
api-version: "1.20.6"
libraries:
 - it.unimi.dsi:fastutil:${versions.fastutil}

permissions:
 enchantableblocks.enchant:
  default: true

commands:
 enchantableblocks:
  usage: /enchantableblocks reload
  description: Command used to control EnchantableBlocks.
  permission: enchantableblocks.admin
