name: EnchantableBlocks

main: com.github.jikoo.enchantableblocks.EnchantableBlocksPlugin
version: ${project.version}
author: Jikoo
api-version: "1.17"
libraries:
 - it.unimi.dsi:fastutil:8.5.4

permissions:
 enchantableblocks.enchant:
  default: true
  children:
   enchantableblocks.enchant.table: true
   enchantableblocks.enchant.anvil: true

commands:
 enchantableblocks:
  usage: /enchantableblocks reload
  description: Command used to control EnchantableBlocks.
  permission: enchantableblocks.admin
