name: EnchantableBlocks

main: com.github.jikoo.enchantableblocks.EnchantableBlocksPlugin
version: ${project.version}
author: Jikoo
api-version: 1.14

permissions:
 enchantableblocks.enchant:
  default: true
  children:
   enchantableblocks.enchant.table: true
   enchantableblocks.enchant.anvil: true
