name: EnchantedFurnace

main: com.github.jikoo.enchantableblocks.EnchantableBlocksPlugin
version: ${project.version}
author: Jikoo

permissions:
 enchantableblocks.enchant:
  default: true
  children:
   enchantableblocks.enchant.table: true
   enchantableblocks.enchant.anvil: true
