name: EnchantedFurnace

main: com.github.jikoo.enchantedfurnace.EnchantedFurnacePlugin
version: ${project.version}
author: Jikoo

permissions:
 enchantedfurnace.enchant:
  default: true
  children:
   enchantedfurnace.enchant.table: true
   enchantedfurnace.enchant.anvil: true
