# http://dev.bukkit.org/bukkit-plugins/enchantedfurnace/
# 
# 
# fortune_list_mode controls the fortune black/whitelist functionality.
# In blacklist mode, the materials specified cannot be affected by fortune.
# In whitelist mode, only the materials specified can be affected by fortune.
# 
# To disable fortune entirely, set fortune_list_mode: whitelist and fortune_list: []
# You should also remove LOOT_BONUS_BLOCKS from furnace_enchantments.
# 
# 
# furnace_enchantments controls which enchantments can be gotten from an enchanting table.
# Enchantments obtained prior to changes will still be present and functional.
fortune_list_mode: blacklist
fortune_list:
- SPONGE
- SMOOTH_BRICK
furnace_enchantments:
- DIG_SPEED
- DURABILITY
- LOOT_BONUS_BLOCKS
- SILK_TOUCH

#UNIMPLEMENTED
#enchantment_incompatibilities:
#- SILK_TOUCH: LOOT_BONUS_BLOCKS
## Enchantability is how easily enchantable an object is.
## leather/wood: 15, stone: 5, iron armor: 9, iron tools: 14, chain: 12, gold armor: 25, gold tools: 22, diamond: 10
#furnace_enchantability: 5
#furnace_durability