name: EnchantedFurnace

main: com.github.jikoo.enchantedfurnace.EnchantedFurnace
version: 1.4.1
author: Jikoo

permissions:
 enchantedfurnace.enchant:
  default: true
  children:
   enchantedfurnace.enchant.table: true
   enchantedfurnace.enchant.anvil: false
