name: EnchantedFurnace

main: com.github.jikoo.enchantedfurnace.EnchantedFurnace
version: 1.5.0
author: Jikoo

permissions:
 enchantedfurnace.enchant:
  default: false
  children:
   enchantedfurnace.enchant.table: true
   enchantedfurnace.enchant.anvil: true
 enchantedfurnace.enchant.anvil:
  default: false
 enchantedfurnace.enchant.table:
  default: true
